# Generated by Django 2.1.5 on 2019-02-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_num', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_input',
            name='num',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
